### ISSUE TITLE
 Godot 4 support planned?

### ISSUE THREAD

**Issue by kragil** [Dracks/GodotGraphQL#1]
Hello,

any plans to support Godot 4?

**Comment by Dracks** [comment]
Well, the project I was going to use this, It's completly stop right now. But since you ask, I will try to get time on that. But Keep in mind that this library is pretty basic as it is of today. 

Also, if somebody wish to do P/R I will be happy to check them and approve it! :)

**Comment by Dracks** [comment]
I merged the changes to make it compatible with godot 4 (I also changed the default branch to main)

**Comment by kragil** [comment]
Cool, thanks a lot! I will have to try it soon. Thanks again!

**Comment by Dracks** [comment]
Nah! thanks to you to use it! I created this small project (without readme) to run it and test it!
https://github.com/Dracks/godot-gql-test

(Also contains a small typescript graphql server)

**Comment by kragil** [comment]
Cool. First, I will try to use it with my https://appwrite.io/ server or with supbase.com. I might even try your test case ;-). I will let you know how that goes. I really don't know why GDscript doesn't have more GraphQL support, maybe everyone is already using C#, I don't know.

**Comment by Dracks** [comment]
I asked in the forum before creating it, and they told me, use C# there is good libraries in C# to use graphql... But I don't like C# :)
