### ISSUE TITLE
Subscriptions support

### ISSUE THREAD

**Issue by Pjort** [Dracks/GodotGraphQL#3]
Do you have any plans to support graphql subscriptions?

**Comment by Dracks** [comment]
I'm sorry to say it, but right now, no... I'm busy in other projects, and supporting subscriptions I expect is more complex, I didn't investigate how they work. But I will be glad to help anybody that know how they work. 

(Now that I think on it, one of the projects I'm working in godot right now at some moment maybe will be usefull to have, still it will be a lot of time until I will need it)

**Comment by Pjort** [comment]
Here is a basic implementation for graphql subscribtion using websockets in python. It is tested and works against a graphql server created with the dotnet hotchocolate.

```
import asyncio
import websockets
import json

async def connect_to_graphql():
    url = "ws://HOST:PORT/graphql/"

    init_message = {
        "type": "connection_init",
        "payload": {}
    }

    subscription_query = {
        "type": "start",
        "id": "1",
        "payload": {
            "query": """subscription {
              onUpdatedData(id: "GUID") {
                name
                value
                timestamp
              }
            }"""
        }
    }

    try:
        async with websockets.connect(url, subprotocols=['graphql-ws']) as websocket:
            print("Connected to the server...")
            
            await websocket.send(json.dumps(init_message))
            print("Init message sent...")
            
            response = await websocket.recv()
            print("Received response to init:", response)
            
            if json.loads(response).get("type") == "connection_ack":
                await websocket.send(json.dumps(subscription_query))
                print("Subscription query sent...")
            
                while True:
                    response = await websocket.recv()
                    print("Received data:", response)
                    
    except Exception as e:
        print("Error:", str(e))
    finally:
        print("Connection closed.")

if __name__ == '__main__':
    asyncio.run(connect_to_graphql())
```

Maybe someone knows if this would easy to port over to GDscript?

**Comment by Dracks** [comment]
I just took a look this morning,maybe with this code I can try to migrate it to godot. Give me some time :)

**Comment by Pjort** [comment]
Sorry, I have gone away from using godot. I am using Godot C# with nuget packages for handling the graphql communication.
